### ISSUE TITLE
NPE on login.

### ISSUE THREAD

**Issue by ChimpGamer** [Maximvdw/SpigotSite#18]
Logging in with or without an account that uses 2fa causes a NPE.

```
        java.lang.NullPointerException
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:103)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:80)
        at nl.chimpgamer.networkmanager.spigotsite.SpigotSite.authenticate(SpigotSite.kt:105)
        at nl.chimpgamer.networkmanager.spigotsite.SpigotSite.loginUser(SpigotSite.kt:56)
        at nl.chimpgamer.networkmanager.spigotsite.SpigotSite.load(SpigotSite.kt:39)
        at nl.chimpgamer.networkmanager.NetworkManager.start(Networkmanager.kt:53)
```

**Comment by bertek41** [comment]
Any news?

**Comment by SanderGielisse** [comment]
Likely caused by [https://proxy.spigotmc.org/282fc8aea2aea1bafdae92dadab1aae939175278?url=https%3A%2F%2Fimages.ctfassets.net%2Fslt3lc6tev37%2F6sN2VXiUaJpjxqVfTbZEJd%2F9a4e13cbf08ce29797167c133c534e1f%2Fimage1.png](url) rather than the simple 5 second wait, so the next job is to break the anti robot check of Google, which entire engineering teams have been working on for the past few years, so I am afraid we have to go find an alternative here.

**Comment by bertek41** [comment]
Then if spigot won't give us an API we have no choice. Will it work if bot opens browser and we pass the robot protection?

**Comment by ChimpGamer** [comment]
Yea this really sucks. @Maximvdw can you fix this?

**Comment by Maximvdw** [comment]
Will check

**Comment by Shin1gamiX** [comment]
Any updates on this?

**Comment by bertek41** [comment]
@Maximvdw any news?

**Comment by toppev** [comment]
https://github.com/Maximvdw/SpigotSite/blob/49c464058f72ed0f9f66782a683e30017a3674ac/src/main/java/be/maximvdw/spigotsite/http/HTTPUnitRequest.java#L42
No longer works as "Cloudflare" is a link (`<a>` tag). Shortening the check to "DDoS protection by" fixes it. The same string is used multiple times (at least in lines 76 and 134)

**Comment by bertek41** [comment]
> https://github.com/Maximvdw/SpigotSite/blob/49c464058f72ed0f9f66782a683e30017a3674ac/src/main/java/be/maximvdw/spigotsite/http/HTTPUnitRequest.java#L42
> 
> 
> No longer works as "Cloudflare" is a link (`<a>` tag). Shortening the check to "DDoS protection by" fixes it. The same string is used multiple times (at least in lines 76 and 134)

This time this error occurs
```
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'name=provider'
        at org.jsoup.select.QueryParser.parse(QueryParser.java:47)
        at org.jsoup.select.Selector.select(Selector.java:92)
        at org.jsoup.nodes.Element.select(Element.java:396)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:105)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:78)
        at be.maximvdw.spigotbuyercheck.beans.SpigotSiteServerBean.init(SpigotSiteServerBean.java:104)
```

**Comment by ChimpGamer** [comment]
> https://github.com/Maximvdw/SpigotSite/blob/49c464058f72ed0f9f66782a683e30017a3674ac/src/main/java/be/maximvdw/spigotsite/http/HTTPUnitRequest.java#L42
> 
> 
> No longer works as "Cloudflare" is a link (`<a>` tag). Shortening the check to "DDoS protection by" fixes it. The same string is used multiple times (at least in lines 76 and 134)

Nice, that's one problem less. After applying that I bumped into this error:
`java.lang.NullPointerException
        at be.maximvdw.spigotsite.user.SpigotUserManager.totpVerification(SpigotUserManager.java:176)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:123)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:80)
be.maximvdw.spigotsite.api.user.exceptions.TwoFactorAuthenticationException
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:125)
        at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:80)`

**Comment by bertek41** [comment]
@ChimpGamer check my pull request

**Comment by ChimpGamer** [comment]
I did but authentication fails in the tests. I'm using the correct username and password and I also use 2FA.
https://pastebin.com/a1tdTnwn

**Comment by bertek41** [comment]
I didn't use the tests but i can login to my account so there is no problem.

**Comment by ChimpGamer** [comment]
With 2FA authentication @bertek41 ?

**Comment by bertek41** [comment]
Yes ofc

**Comment by ChimpGamer** [comment]
I always get the TwoFactorAuthenticationException

**Comment by bertek41** [comment]
Did you build latest commit?

**Comment by ChimpGamer** [comment]
I did.

**Comment by bertek41** [comment]
![image](https://user-images.githubusercontent.com/20637793/84591616-917d2e80-ae48-11ea-94e7-e907fc951015.png)

**Comment by ChimpGamer** [comment]
I think I've found the problem. I'll close this issue now.

**Comment by ChimpGamer** [comment]
And again Cloudflare managed to also break this Spigot Forum api again.
Same error but now it's on line 101 of SpigotUserManager class

**Comment by ChimpGamer** [comment]
And for some reason it magically works again. WTF cloudflare...
